channels:
  - conda-forge
dependencies:
  - r-base=4.1.3
  - r-rcpp
  - r-tinytex
  - r-tidyverse
  - r-knitr
  - r-tidymodels
  - r-kernlab
  - r-kknn
  - r-glmnet
  - r-leaps
  - r-car
  - r-mlbench
  - r-skimr
  - r-klar
  - r-rpart
  - r-rpart.plot
  - r-xgboost
  - r-randomforest
  - r-vip
  - r-keras
  - r-tensorflow
